channels:
- conda-forge
dependencies:
- python=3.12.2
- pip<=23.2.1
- pip:
  - mlflow==2.16.2
  - catboost==1.2.7
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.5.1
  - scipy==1.14.0
name: mlflow-env
